import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy import create_engine, pool

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# The same variables `api/app/db/connection.py` reads.
DB_HOST = os.getenv("DB_HOST", "127.0.0.1")
DB_PORT = os.getenv("DB_PORT", "3306")
DB_USER = os.getenv("DB_USER", "admin_zoopark")
DB_PASSWORD = os.getenv("DB_PASSWORD", "")
DB_NAME = os.getenv("DB_NAME", "zoopark")

DB_URL = os.getenv("DB_URL") or f"mysql+pymysql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"

# The schema is defined by the revisions, not autogenerated from the ORM. `models.py` is
# the source of truth for the code; a revision is the source of truth for the database,
# and `test_migration_matches_models` asserts the two agree.
target_metadata = None


def run_migrations_online() -> None:
    engine = create_engine(
        DB_URL,
        poolclass=pool.NullPool,
        connect_args=(
            {}
            if DB_URL.startswith("sqlite")
            else {"connect_timeout": 10, "read_timeout": 30, "write_timeout": 30}
        ),
    )
    with engine.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


run_migrations_online()
