from __future__ import annotations


ZOOPARK_USERS_TABLE = "zoopark_users"
ZOOPARK_SEASONS_TABLE = "zoopark_seasons"
ZOOPARK_PLAYER_SEASONS_TABLE = "zoopark_player_seasons"
ZOOPARK_ITEMS_TABLE = "zoopark_items"
ZOOPARK_FORGE_SETS_TABLE = "zoopark_forge_sets"
ZOOPARK_FORGE_SET_ITEMS_TABLE = "zoopark_forge_set_items"
ZOOPARK_UNITY_TABLE = "zoopark_unity"
ZOOPARK_SICK_EVENTS_TABLE = "zoopark_sick_events"
ZOOPARK_MERCHANT_OFFERS_TABLE = "zoopark_merchant_offers"
ZOOPARK_PACK_ANIMALS_TABLE = "zoopark_pack_animals"
ZOOPARK_PACK_OPENINGS_TABLE = "zoopark_pack_openings"
ZOOPARK_LOCALITIES_TABLE = "zoopark_player_localities"
ZOOPARK_EXPEDITIONS_TABLE = "zoopark_expeditions"
ZOOPARK_EXPEDITION_ANIMALS_TABLE = "zoopark_expedition_animals"
ZOOPARK_BREEDING_EVENTS_TABLE = "zoopark_breeding_events"
ZOOPARK_MP_GAMES_TABLE = "zoopark_mp_games"
ZOOPARK_SOLO_STATS_TABLE = "zoopark_solo_stats"
ZOOPARK_COCKTAIL_SESSIONS_TABLE = "zoopark_cocktail_sessions"
ZOOPARK_TRANSFER_LINKS_TABLE = "zoopark_transfer_links"
ZOOPARK_REFERRALS_TABLE = "zoopark_referrals"
ZOOPARK_BOOTSTRAP_META_TABLE = "zoopark_bootstrap_meta"
