from __future__ import annotations


ZOOPARK_USERS_TABLE = "zoopark_users"
ZOOPARK_ANIMALS_TABLE = "zoopark_animals"
ZOOPARK_AVIARIES_TABLE = "zoopark_aviaries"
ZOOPARK_ITEMS_TABLE = "zoopark_items"
ZOOPARK_UNITY_TABLE = "zoopark_unity"
ZOOPARK_EXTRA_TABLE = "zoopark_webapp_extra"
ZOOPARK_SICK_EVENTS_TABLE = "zoopark_sick_events"
ZOOPARK_MERCHANTS_TABLE = "zoopark_merchants"
ZOOPARK_PACK_ANIMALS_TABLE = "zoopark_pack_animals"
ZOOPARK_LOCALITIES_TABLE = "zoopark_player_localities"
ZOOPARK_EXPEDITIONS_TABLE = "zoopark_expeditions"
ZOOPARK_EXPEDITION_ANIMALS_TABLE = "zoopark_expedition_animals"
ZOOPARK_MP_GAMES_TABLE = "zoopark_mp_games"
ZOOPARK_SOLO_STATS_TABLE = "zoopark_solo_stats"
ZOOPARK_COCKTAIL_SESSIONS_TABLE = "zoopark_cocktail_sessions"
ZOOPARK_TRANSFER_LINKS_TABLE = "zoopark_transfer_links"
ZOOPARK_REFERRALS_TABLE = "zoopark_referrals"
